# Generated by Django 4.2.4 on 2023-08-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=55, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone_number', models.IntegerField(max_length=60, verbose_name='Введите номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('age', models.IntegerField(max_length=15, verbose_name='Введите сколька вам лет')),
                ('wallet_adress', models.CharField(max_length=155, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Посты',
            },
        ),
    ]
